version: '2.4'

services:

  unit-tests-3-7:
    build:
      context: .
      dockerfile: test/Dockerfile_3.7
    volumes:
     - .:/undictify
    working_dir: /undictify
    entrypoint: ./test/install_from_local_and_run_code_checks.sh

  unit-tests-3-8:
    build:
      context: .
      dockerfile: test/Dockerfile_3.8
    volumes:
     - .:/undictify
    working_dir: /undictify
    entrypoint: ./test/install_from_local_and_run_code_checks.sh
